name: Use Shared Workflow

on:
  push:
    branches:
      - main

jobs:
  call-shared-workflow:
    uses: sds9-org/shared-actions/.github/workflows/shared-workflow.yml@main
    with:
      # example_input: ${{ toJSON(github) }}
      example_input: 'Hello, World!'